name: Continuous Deployment (CD) to Koyeb

on:
  push:
    branches:
      - main
      - module-2-exercise

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Koyeb login
        run: koyeb login --api-token ${{ secrets.KOYEB_API_TOKEN }}

      - name: Build Docker image
        run: docker build -t advshop:latest .

      - name: Deploy to Koyeb
        run: |
          koyeb service update \
            --app advshop \
            --service advshop \
            --image advshop:latest \
            --region "ams" \
            --health-check-http "/"

      - name: Wait for service to be healthy
        run: |
          echo "Waiting for Koyeb service to be healthy..."
          sleep 15